server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp18r248ij4z16o5ogo.mysql.rds.aliyuncs.com:3306/spring-cloud-study?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: slayerd
    password: Songyudong061618
  application:
    name: borrowservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1234
#        server-addr: localhost:8801
        ephemeral: false
#        cluster-name: Shanghai
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8803
      web-context-unify: false
      block-page: /blocked
#开启feign支持熔断的功能
feign:
#  circuitbreaker:
#    enabled: true
  sentinel:   #sentinel也支持开启feign的降级功能
    enabled: true
